### ISSUE TITLE
HTTP status code 429 when connecting to Reddit

### ISSUE THREAD

**Issue by kamok** [karl-b/reddit-api#2]
Hello,

I tried to create a new connection to reddit through.

user = Reddit::Services::User.new("redditusername", "redditpassword", "clientID", "secret", "appname")

RestClient::RequestFailed: HTTP status code 429
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:50:in `return!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in`process_result'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:853:in`start'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in`execute'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/reddit-api-0.1.2/lib/reddit/internal/connection.rb:51:in`sign_in'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/reddit-api-0.1.2/lib/reddit/services/user.rb:18:in `initialize'
        from (irb):3:in`new'
        from (irb):3
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:110:in `start'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in`start'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in`run_command!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in`require'
        from bin/rails:4:in `<main>'irb(main):004:0> user = Reddit::Services::User.new("123karmawarrior", "123456", "cLR6CKaveehIfg", "yvtGdMrWomd_5LW8BTyHk08fk9w", "superbowl")
RuntimeError: Error Invalid Credentials
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/reddit-api-0.1.2/lib/reddit/internal/connection.rb:60:in`sign_in'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/reddit-api-0.1.2/lib/reddit/services/user.rb:18:in `initialize'
        from (irb):4:in`new'
        from (irb):4
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:110:in `start'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in`start'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in`run_command!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in`require'
        from bin/rails:4:in `<main>'
irb(main):005:0> user = Reddit::Services::User.new("123karmawarrior", "123456", "cLR6CKaveehIfg", "yvtGdMrWomd_5LW8BTyHk08fk9w", "superbowl")
RestClient::RequestFailed: HTTP status code 429
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:50:in`return!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in`block in transmit'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:853:in `start'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in`transmit'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in`execute'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/reddit-api-0.1.2/lib/reddit/internal/connection.rb:51:in `sign_in'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/reddit-api-0.1.2/lib/reddit/services/user.rb:18:in`initialize'
        from (irb):5:in `new'
        from (irb):5
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:110:in`start'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in `start'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in`console'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in`<top (required)>'
        from bin/rails:4:in `require'

**Comment by erniebrodeur** [comment]
RestClient::RequestFailed: HTTP status code 429

https://httpstatuses.com/429

Don't open so many connections at once.
